### ISSUE TITLE
Question about model performance of MFH_Coatt_Glove

### ISSUE THREAD

**Issue by nightlyjourney** [asdf0982/vqa-mfb.pytorch#1]
Hi, I have perprocess the Genome and VQA dataset based on instructions here (https://github.com/akirafukui/vqa-mcb/tree/master/preprocess) and ran 'train_mfh_coatt_glove.py'. However the accuracy only achieved 62.36% at the best, still far from the 68.78%. So could you please give me some suggestions on how to gain a better accuracy? I would truly appreciated.

FYI, I only changed the setting of IMG_FEAT_SIZE in the 'config.py' from 100 to 196, as in the data preprocss part it extracts the 14*14 image features.

**Comment by asdf0982** [comment]
Hi, I extract the [bottom-up features](https://arxiv.org/abs/1707.07998) as input features. Here 'IMG_FEAT_SIZE = 100' means there are k(up to 100) boxes.

**Comment by nightlyjourney** [comment]
Hi Wang, thanks for your reply. I knew that bottom-up features are used in MFH and I preprocessed the image data via ResNet152. I just wonder why there is such a big difference of performace between mine and yours. Could you please give me some hints on how to improve it? Thanks a lot.

**Comment by asdf0982** [comment]
Hi, The result of MFH+CoAtt+GloVe (68.78) is trained with train+val sets, tested with test-dev sets. [CodaLab - VQA Real Image Challenge](https://competitions.codalab.org/competitions/6961#results)
I train the model with train-set and verify with val-set that results in 64.8%. I think 62.36 is because ResNet152 features are not as good as bottom-up features.

**Comment by nightlyjourney** [comment]
Hi Wang, thanks for your timely reply. But how did you extract the bottom-up features? Would you be willing to share that code? Thanks.

**Comment by asdf0982** [comment]
@NightlyJourney  Hi Ding, I modified a few lines of the ['generate_tsv.py'](https://github.com/peteanderson80/bottom-up-attention/blob/master/tools/generate_tsv.py) to get npz feature files. And I think maybe [the project of Bottom-up features](https://github.com/peteanderson80/bottom-up-attention) can help you too :)

**Comment by nightlyjourney** [comment]
Hi Wang. Got it, thank you so much for your help :)

**Comment by NightlyJourney** [comment]
Hi Wang, it looks the VQA challenge concerning 2015 dataset is ended on 2016, given the situation, could you please tell me how can I submite the result file on it? I have tried here (https://competitions.codalab.org/competitions/6961#participate) but after I click submit button and choose the result file, nothing changed.

**Comment by NightlyJourney** [comment]
I figure it out, truly sorry for the disturbance.

**Comment by nightlyjourney** [comment]
Hi Wang, I noticed that while training, the label for a training sample is in the form of  [ 0.0000  0.0000  0.0000  ...   0.2000  0.8000  0.0000], could you please tell me what this vector stands for? why it is not a one-hot vector?

Also, I found that while validating, the label for a validation sample is just a value like 2998, could you please also tell me what does it stands for? why the label for training and validating are in different formats? Thanks a lot.
