### ISSUE TITLE
the dimension of img_feat looks strange in mfh_baseline , I found the model can't process an image feature vector whose size is (batch_size, 2048, 14, 14) 

### ISSUE THREAD

**Issue by 2003pro** [asdf0982/vqa-mfb.pytorch#2]
After processing preprocess module from https://github.com/akirafukui/vqa-mcb , I get image feature files . But when I try to transfer it to the data_provider , I find the numpy array to save img feature have a wrong size. So I resize this array from (batch_size*2048) to (batch_size*2048*14*14) . But it still had something wrong when the feature array was transferred to the forward function in nn Module of mfh_baseline.py . 
How did you change the feature array from 2048*14*14 into 2048?

**Comment by asdf0982** [comment]
Hi, I use ResNet152-pool5 features(batch_size, 2048). 
If your features are ResNet-res5c features(batch_size, 2048, 14, 14), maybe need to add an average pool layer to get pool5 features or modify the vqa-mcb code to get pool5 features. :)

**Comment by 2003pro** [comment]
Thanks for your reply.I just read the mfh model's paper again and find the pool5 feature had been mentioned in the baseline model's intro-part. I got your reply at the same time . I get the point from both the paper and you, you know , that feels great . :)
