### ISSUE TITLE
Why don't you release VQA-2.0 result?

### ISSUE THREAD

**Issue by bezorro** [asdf0982/vqa-mfb.pytorch#6]
Hi Wang, thanks for you helpful code.

Did you try to replicate your 'MFH+CoAtt+GloVe (FRCN img features)' on VQA-2.0 ?
btw, when replicating the result of 68.78% in VQA-1.0, did you train on VG+vqa-train+vqa+val or just simply train on vqa-train+vqa-val? maybe that 's the reason you not able to replicate on MFH-coatt-glove?

**Comment by asdf0982** [comment]
@bezorro yes, I trained a model using only the train-set in VQA-2.0, and the acc is about 0.8 worse than the [caffe version](https://github.com/yuzcccc/vqa-mfb)(using the same train-set).

**Comment by bezorro** [comment]
So, do you mean that you can not replicate MFH+CoAtt+GloVe (FRCN img features) VQA-2.0 yet?
Do you know the reason?

**Comment by asdf0982** [comment]
@bezorro yes, i have already said it in the README. i dont know where the bug is

**Comment by bezorro** [comment]
@asdf0982 I see, thanks.
